## 反向传递
* 构造计算图 <br/>
* 前向：执行图，储存中间结果 <br/>
* 反向：从相反方向执行图，去除不需要的枝 <br/>

## 复杂度
* 计算复杂度：O(n)，n是操作子个数，通常正向与反向类似  
* 内存复杂度：O(n)，因为需要存储正向的所有中间结果

## 自动求导

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True) # 在计算y关于x的梯度之前，需要一个地方存储梯度
x.grad

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward() # 调用反向传播函数，计算y关于x每个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# 默认情况下，PyTorch会累计梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad


tensor([1., 1., 1., 1.])

In [8]:
# 对非标量调用`backward`需要传入一个`gradient`参数
x.grad.zero_()
y = x * x 
y.sum().backward()# 转化为标量
x.grad

tensor([0., 2., 4., 6.])

In [9]:
# 将某些计算移动到记录的计算图外
x.grad.zero_()
y = x * x
u = y.detach() # y不视作x的函数

z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [20]:
x.grad.zero_()
def f(a):
    b = a * 2
    while b.norm()<1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c 

a = torch.randn(size=(), requires_grad=True) # 标量，需要梯度
d = f(a)
d.backward()

a.grad == d / a

tensor(True)